/* ===============================================================================
PostgreSQL Warehouse SCD2 Validation Queries
================================================================================

Purpose:
- Validate SCD Type 2 correctness for warehouse.dim_customer,
  warehouse.dim_product, and warehouse.dim_campaign.
- Prove that facts join to the correct historical dimension versions.
- Catch duplicate current rows, invalid effective windows, overlapping ranges,
  duplicate surrogate keys, missing/unknown surrogate keys in facts, and
  reprocessing/idempotency failures.
- Store validation results in audit.scd2_validation_results.

Expected result:
- Every validation row should return PASS.
- Any FAIL row means warehouse history is not trustworthy yet.

================================================================================ */

BEGIN;

CREATE SCHEMA IF NOT EXISTS audit;

DROP TABLE IF EXISTS audit.scd2_validation_results CASCADE;

CREATE TABLE audit.scd2_validation_results (
    validation_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_run_id TEXT NOT NULL,
    check_category TEXT NOT NULL,
    check_name TEXT NOT NULL,
    checked_entity TEXT NOT NULL,
    failed_row_count BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PASS', 'FAIL')),
    severity TEXT NOT NULL DEFAULT 'ERROR',
    details TEXT,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE audit.scd2_validation_results IS
'SCD2 validation audit table. Stores pass/fail counts for warehouse historical correctness checks.';

-- =============================================================================
-- 1. Only one current row per natural key
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_current_row_violations AS
SELECT
    'only_one_current_row_per_customer_id' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    customer_id AS natural_key,
    NULL::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'current_row_count=' || COUNT(*) FILTER (WHERE is_current) AS issue_details
FROM warehouse.dim_customer
WHERE customer_id <> 'UNKNOWN'
GROUP BY customer_id
HAVING COUNT(*) FILTER (WHERE is_current) <> 1

UNION ALL

SELECT
    'only_one_current_row_per_product_id' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    product_id AS natural_key,
    NULL::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'current_row_count=' || COUNT(*) FILTER (WHERE is_current) AS issue_details
FROM warehouse.dim_product
WHERE product_id <> 'UNKNOWN'
GROUP BY product_id
HAVING COUNT(*) FILTER (WHERE is_current) <> 1

UNION ALL

SELECT
    'only_one_current_row_per_campaign_id' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    campaign_id AS natural_key,
    NULL::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'current_row_count=' || COUNT(*) FILTER (WHERE is_current) AS issue_details
FROM warehouse.dim_campaign
WHERE campaign_id <> 'UNKNOWN'
GROUP BY campaign_id
HAVING COUNT(*) FILTER (WHERE is_current) <> 1;

-- =============================================================================
-- 2. No invalid effective date ranges
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_invalid_effective_range_violations AS
SELECT
    'invalid_customer_effective_range' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    customer_id AS natural_key,
    customer_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'effective_from=' || effective_from || ', effective_to=' || effective_to AS issue_details
FROM warehouse.dim_customer
WHERE effective_from IS NULL
   OR effective_to IS NULL
   OR effective_to <= effective_from

UNION ALL

SELECT
    'invalid_product_effective_range' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    product_id AS natural_key,
    product_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'effective_from=' || effective_from || ', effective_to=' || effective_to AS issue_details
FROM warehouse.dim_product
WHERE effective_from IS NULL
   OR effective_to IS NULL
   OR effective_to <= effective_from

UNION ALL

SELECT
    'invalid_campaign_effective_range' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    campaign_id AS natural_key,
    campaign_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'effective_from=' || effective_from || ', effective_to=' || effective_to AS issue_details
FROM warehouse.dim_campaign
WHERE effective_from IS NULL
   OR effective_to IS NULL
   OR effective_to <= effective_from;

-- =============================================================================
-- 3. No overlapping effective date ranges
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_overlapping_range_violations AS
SELECT
    'overlapping_customer_effective_ranges' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    a.customer_id AS natural_key,
    a.customer_sk::TEXT || ' overlaps ' || b.customer_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'a=[' || a.effective_from || ', ' || a.effective_to || '), b=['
        || b.effective_from || ', ' || b.effective_to || ')' AS issue_details
FROM warehouse.dim_customer a
JOIN warehouse.dim_customer b
    ON a.customer_id = b.customer_id
   AND a.customer_sk < b.customer_sk
   AND a.customer_id <> 'UNKNOWN'
   AND a.effective_from < b.effective_to
   AND b.effective_from < a.effective_to

UNION ALL

SELECT
    'overlapping_product_effective_ranges' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    a.product_id AS natural_key,
    a.product_sk::TEXT || ' overlaps ' || b.product_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'a=[' || a.effective_from || ', ' || a.effective_to || '), b=['
        || b.effective_from || ', ' || b.effective_to || ')' AS issue_details
FROM warehouse.dim_product a
JOIN warehouse.dim_product b
    ON a.product_id = b.product_id
   AND a.product_sk < b.product_sk
   AND a.product_id <> 'UNKNOWN'
   AND a.effective_from < b.effective_to
   AND b.effective_from < a.effective_to

UNION ALL

SELECT
    'overlapping_campaign_effective_ranges' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    a.campaign_id AS natural_key,
    a.campaign_sk::TEXT || ' overlaps ' || b.campaign_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'a=[' || a.effective_from || ', ' || a.effective_to || '), b=['
        || b.effective_from || ', ' || b.effective_to || ')' AS issue_details
FROM warehouse.dim_campaign a
JOIN warehouse.dim_campaign b
    ON a.campaign_id = b.campaign_id
   AND a.campaign_sk < b.campaign_sk
   AND a.campaign_id <> 'UNKNOWN'
   AND a.effective_from < b.effective_to
   AND b.effective_from < a.effective_to;

-- =============================================================================
-- 4. No duplicate surrogate keys
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_duplicate_surrogate_key_violations AS
SELECT
    'duplicate_customer_sk' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    NULL::TEXT AS natural_key,
    customer_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_customer
GROUP BY customer_sk
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_product_sk' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    NULL::TEXT AS natural_key,
    product_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_product
GROUP BY product_sk
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_campaign_sk' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    NULL::TEXT AS natural_key,
    campaign_sk::TEXT AS surrogate_key,
    NULL::TEXT AS fact_key,
    'duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_campaign
GROUP BY campaign_sk
HAVING COUNT(*) > 1;

-- =============================================================================
-- 5. No missing or orphaned customer_sk/product_sk/campaign_sk in facts
--
-- Important project convention:
-- - customer_sk/product_sk/campaign_sk = 0 is allowed ONLY when it references
--   the explicit UNKNOWN row in the corresponding dimension.
-- - NULL keys are failures.
-- - Keys with no matching dimension row are failures.
--
-- Unknown usage is reported separately, not hidden.
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_missing_fact_surrogate_key_violations AS
SELECT
    'missing_or_orphan_customer_sk_in_fact_orders' AS check_name,
    'warehouse.fact_orders' AS checked_entity,
    NULL::TEXT AS natural_key,
    fo.customer_sk::TEXT AS surrogate_key,
    fo.order_id AS fact_key,
    'order_id=' || fo.order_id AS issue_details
FROM warehouse.fact_orders fo
LEFT JOIN warehouse.dim_customer dc
    ON fo.customer_sk = dc.customer_sk
WHERE fo.customer_sk IS NULL
   OR dc.customer_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_campaign_sk_in_fact_orders' AS check_name,
    'warehouse.fact_orders' AS checked_entity,
    NULL::TEXT AS natural_key,
    fo.campaign_sk::TEXT AS surrogate_key,
    fo.order_id AS fact_key,
    'order_id=' || fo.order_id AS issue_details
FROM warehouse.fact_orders fo
LEFT JOIN warehouse.dim_campaign dc
    ON fo.campaign_sk = dc.campaign_sk
WHERE fo.campaign_sk IS NULL
   OR dc.campaign_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_customer_sk_in_fact_order_items' AS check_name,
    'warehouse.fact_order_items' AS checked_entity,
    NULL::TEXT AS natural_key,
    foi.customer_sk::TEXT AS surrogate_key,
    foi.order_item_nk AS fact_key,
    'order_item_nk=' || foi.order_item_nk AS issue_details
FROM warehouse.fact_order_items foi
LEFT JOIN warehouse.dim_customer dc
    ON foi.customer_sk = dc.customer_sk
WHERE foi.customer_sk IS NULL
   OR dc.customer_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_product_sk_in_fact_order_items' AS check_name,
    'warehouse.fact_order_items' AS checked_entity,
    NULL::TEXT AS natural_key,
    foi.product_sk::TEXT AS surrogate_key,
    foi.order_item_nk AS fact_key,
    'order_item_nk=' || foi.order_item_nk AS issue_details
FROM warehouse.fact_order_items foi
LEFT JOIN warehouse.dim_product dp
    ON foi.product_sk = dp.product_sk
WHERE foi.product_sk IS NULL
   OR dp.product_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_campaign_sk_in_fact_campaign_spend' AS check_name,
    'warehouse.fact_campaign_spend' AS checked_entity,
    NULL::TEXT AS natural_key,
    fcs.campaign_sk::TEXT AS surrogate_key,
    fcs.campaign_spend_nk AS fact_key,
    'campaign_spend_nk=' || fcs.campaign_spend_nk AS issue_details
FROM warehouse.fact_campaign_spend fcs
LEFT JOIN warehouse.dim_campaign dc
    ON fcs.campaign_sk = dc.campaign_sk
WHERE fcs.campaign_sk IS NULL
   OR dc.campaign_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_customer_sk_in_fact_web_events' AS check_name,
    'warehouse.fact_web_events' AS checked_entity,
    NULL::TEXT AS natural_key,
    fwe.customer_sk::TEXT AS surrogate_key,
    fwe.event_id AS fact_key,
    'event_id=' || fwe.event_id AS issue_details
FROM warehouse.fact_web_events fwe
LEFT JOIN warehouse.dim_customer dc
    ON fwe.customer_sk = dc.customer_sk
WHERE fwe.customer_sk IS NULL
   OR dc.customer_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_product_sk_in_fact_web_events' AS check_name,
    'warehouse.fact_web_events' AS checked_entity,
    NULL::TEXT AS natural_key,
    fwe.product_sk::TEXT AS surrogate_key,
    fwe.event_id AS fact_key,
    'event_id=' || fwe.event_id AS issue_details
FROM warehouse.fact_web_events fwe
LEFT JOIN warehouse.dim_product dp
    ON fwe.product_sk = dp.product_sk
WHERE fwe.product_sk IS NULL
   OR dp.product_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_campaign_sk_in_fact_web_events' AS check_name,
    'warehouse.fact_web_events' AS checked_entity,
    NULL::TEXT AS natural_key,
    fwe.campaign_sk::TEXT AS surrogate_key,
    fwe.event_id AS fact_key,
    'event_id=' || fwe.event_id AS issue_details
FROM warehouse.fact_web_events fwe
LEFT JOIN warehouse.dim_campaign dc
    ON fwe.campaign_sk = dc.campaign_sk
WHERE fwe.campaign_sk IS NULL
   OR dc.campaign_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_customer_sk_in_fact_conversions' AS check_name,
    'warehouse.fact_conversions' AS checked_entity,
    NULL::TEXT AS natural_key,
    fc.customer_sk::TEXT AS surrogate_key,
    fc.conversion_nk AS fact_key,
    'conversion_nk=' || fc.conversion_nk AS issue_details
FROM warehouse.fact_conversions fc
LEFT JOIN warehouse.dim_customer dc
    ON fc.customer_sk = dc.customer_sk
WHERE fc.customer_sk IS NULL
   OR dc.customer_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_product_sk_in_fact_conversions' AS check_name,
    'warehouse.fact_conversions' AS checked_entity,
    NULL::TEXT AS natural_key,
    fc.product_sk::TEXT AS surrogate_key,
    fc.conversion_nk AS fact_key,
    'conversion_nk=' || fc.conversion_nk AS issue_details
FROM warehouse.fact_conversions fc
LEFT JOIN warehouse.dim_product dp
    ON fc.product_sk = dp.product_sk
WHERE fc.product_sk IS NULL
   OR dp.product_sk IS NULL

UNION ALL

SELECT
    'missing_or_orphan_campaign_sk_in_fact_conversions' AS check_name,
    'warehouse.fact_conversions' AS checked_entity,
    NULL::TEXT AS natural_key,
    fc.campaign_sk::TEXT AS surrogate_key,
    fc.conversion_nk AS fact_key,
    'conversion_nk=' || fc.conversion_nk AS issue_details
FROM warehouse.fact_conversions fc
LEFT JOIN warehouse.dim_campaign dc
    ON fc.campaign_sk = dc.campaign_sk
WHERE fc.campaign_sk IS NULL
   OR dc.campaign_sk IS NULL;


CREATE OR REPLACE VIEW audit.v_scd2_unknown_surrogate_key_usage AS
SELECT 'warehouse.fact_orders.customer_sk_unknown' AS usage_name, COUNT(*) AS row_count
FROM warehouse.fact_orders
WHERE customer_sk = 0

UNION ALL
SELECT 'warehouse.fact_orders.campaign_sk_unknown', COUNT(*)
FROM warehouse.fact_orders
WHERE campaign_sk = 0

UNION ALL
SELECT 'warehouse.fact_order_items.customer_sk_unknown', COUNT(*)
FROM warehouse.fact_order_items
WHERE customer_sk = 0

UNION ALL
SELECT 'warehouse.fact_order_items.product_sk_unknown', COUNT(*)
FROM warehouse.fact_order_items
WHERE product_sk = 0

UNION ALL
SELECT 'warehouse.fact_campaign_spend.campaign_sk_unknown', COUNT(*)
FROM warehouse.fact_campaign_spend
WHERE campaign_sk = 0

UNION ALL
SELECT 'warehouse.fact_web_events.customer_sk_unknown', COUNT(*)
FROM warehouse.fact_web_events
WHERE customer_sk = 0

UNION ALL
SELECT 'warehouse.fact_web_events.product_sk_unknown', COUNT(*)
FROM warehouse.fact_web_events
WHERE product_sk = 0

UNION ALL
SELECT 'warehouse.fact_web_events.campaign_sk_unknown', COUNT(*)
FROM warehouse.fact_web_events
WHERE campaign_sk = 0

UNION ALL
SELECT 'warehouse.fact_conversions.customer_sk_unknown', COUNT(*)
FROM warehouse.fact_conversions
WHERE customer_sk = 0

UNION ALL
SELECT 'warehouse.fact_conversions.product_sk_unknown', COUNT(*)
FROM warehouse.fact_conversions
WHERE product_sk = 0

UNION ALL
SELECT 'warehouse.fact_conversions.campaign_sk_unknown', COUNT(*)
FROM warehouse.fact_conversions
WHERE campaign_sk = 0;

-- =============================================================================
-- 6. Fact dates must fall inside dimension effective date ranges
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_fact_date_range_violations AS
SELECT
    'fact_orders_customer_date_outside_customer_scd2_range' AS check_name,
    'warehouse.fact_orders -> warehouse.dim_customer' AS checked_entity,
    dc.customer_id AS natural_key,
    fo.customer_sk::TEXT AS surrogate_key,
    fo.order_id AS fact_key,
    'order_timestamp=' || COALESCE(fo.order_timestamp::TEXT, 'NULL')
        || ', customer_range=[' || dc.effective_from || ', ' || dc.effective_to || ')' AS issue_details
FROM warehouse.fact_orders fo
JOIN warehouse.dim_customer dc ON fo.customer_sk = dc.customer_sk
WHERE fo.order_timestamp IS NULL
   OR fo.order_timestamp < dc.effective_from
   OR fo.order_timestamp >= dc.effective_to

UNION ALL

SELECT
    'fact_orders_campaign_date_outside_campaign_scd2_range' AS check_name,
    'warehouse.fact_orders -> warehouse.dim_campaign' AS checked_entity,
    dca.campaign_id AS natural_key,
    fo.campaign_sk::TEXT AS surrogate_key,
    fo.order_id AS fact_key,
    'order_timestamp=' || COALESCE(fo.order_timestamp::TEXT, 'NULL')
        || ', campaign_range=[' || dca.effective_from || ', ' || dca.effective_to || ')' AS issue_details
FROM warehouse.fact_orders fo
JOIN warehouse.dim_campaign dca ON fo.campaign_sk = dca.campaign_sk
WHERE fo.order_timestamp IS NULL
   OR fo.order_timestamp < dca.effective_from
   OR fo.order_timestamp >= dca.effective_to

UNION ALL

SELECT
    'fact_order_items_customer_date_outside_customer_scd2_range' AS check_name,
    'warehouse.fact_order_items -> warehouse.dim_customer' AS checked_entity,
    dc.customer_id AS natural_key,
    foi.customer_sk::TEXT AS surrogate_key,
    foi.order_item_nk AS fact_key,
    'order_timestamp=' || COALESCE(foi.order_timestamp::TEXT, 'NULL')
        || ', customer_range=[' || dc.effective_from || ', ' || dc.effective_to || ')' AS issue_details
FROM warehouse.fact_order_items foi
JOIN warehouse.dim_customer dc ON foi.customer_sk = dc.customer_sk
WHERE foi.order_timestamp IS NULL
   OR foi.order_timestamp < dc.effective_from
   OR foi.order_timestamp >= dc.effective_to

UNION ALL

SELECT
    'fact_order_items_product_date_outside_product_scd2_range' AS check_name,
    'warehouse.fact_order_items -> warehouse.dim_product' AS checked_entity,
    dp.product_id AS natural_key,
    foi.product_sk::TEXT AS surrogate_key,
    foi.order_item_nk AS fact_key,
    'order_timestamp=' || COALESCE(foi.order_timestamp::TEXT, 'NULL')
        || ', product_range=[' || dp.effective_from || ', ' || dp.effective_to || ')' AS issue_details
FROM warehouse.fact_order_items foi
JOIN warehouse.dim_product dp ON foi.product_sk = dp.product_sk
WHERE foi.order_timestamp IS NULL
   OR foi.order_timestamp < dp.effective_from
   OR foi.order_timestamp >= dp.effective_to

UNION ALL

SELECT
    'fact_campaign_spend_campaign_date_outside_campaign_scd2_range' AS check_name,
    'warehouse.fact_campaign_spend -> warehouse.dim_campaign' AS checked_entity,
    dca.campaign_id AS natural_key,
    fcs.campaign_sk::TEXT AS surrogate_key,
    fcs.campaign_spend_nk AS fact_key,
    'spend_date=' || COALESCE(fcs.spend_date::TEXT, 'NULL')
        || ', campaign_range=[' || dca.effective_from || ', ' || dca.effective_to || ')' AS issue_details
FROM warehouse.fact_campaign_spend fcs
JOIN warehouse.dim_campaign dca ON fcs.campaign_sk = dca.campaign_sk
WHERE fcs.spend_date IS NULL
   OR fcs.spend_date::TIMESTAMP < dca.effective_from
   OR fcs.spend_date::TIMESTAMP >= dca.effective_to;


-- =============================================================================
-- 7. Null tracked attributes handling
--    This catches duplicate versions that collapse to the same null-normalized
--    tracked attribute state.
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_null_tracked_attribute_violations AS
SELECT
    'duplicate_customer_versions_after_null_normalization' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    customer_id AS natural_key,
    STRING_AGG(customer_sk::TEXT, ', ' ORDER BY customer_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_customer
WHERE customer_id <> 'UNKNOWN'
GROUP BY
    customer_id,
    effective_from,
    effective_to,
    is_current,
    COALESCE(customer_name, '__NULL__'),
    COALESCE(email, '__NULL__'),
    COALESCE(gender, '__NULL__'),
    COALESCE(age::TEXT, '__NULL__'),
    COALESCE(membership_tier, '__NULL__'),
    COALESCE(loyalty_points::TEXT, '__NULL__'),
    COALESCE(preferred_language, '__NULL__'),
    COALESCE(customer_segment, '__NULL__'),
    COALESCE(is_prime_user::TEXT, '__NULL__'),
    COALESCE(home_city, '__NULL__'),
    COALESCE(home_state, '__NULL__'),
    COALESCE(country, '__NULL__')
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_product_versions_after_null_normalization' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    product_id AS natural_key,
    STRING_AGG(product_sk::TEXT, ', ' ORDER BY product_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_product
WHERE product_id <> 'UNKNOWN'
GROUP BY
    product_id,
    effective_from,
    effective_to,
    is_current,
    COALESCE(product_name, '__NULL__'),
    COALESCE(category, '__NULL__'),
    COALESCE(brand, '__NULL__'),
    COALESCE(original_price::TEXT, '__NULL__'),
    COALESCE(current_price::TEXT, '__NULL__'),
    COALESCE(inventory_remaining::TEXT, '__NULL__')
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_campaign_versions_after_null_normalization' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    campaign_id AS natural_key,
    STRING_AGG(campaign_sk::TEXT, ', ' ORDER BY campaign_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_campaign
WHERE campaign_id <> 'UNKNOWN'
GROUP BY
    campaign_id,
    effective_from,
    effective_to,
    is_current,
    COALESCE(campaign_name, '__NULL__'),
    COALESCE(campaign_type, '__NULL__'),
    COALESCE(channel, '__NULL__'),
    COALESCE(traffic_source, '__NULL__'),
    COALESCE(target_segment, '__NULL__'),
    COALESCE(campaign_start_date::TEXT, '__NULL__'),
    COALESCE(campaign_end_date::TEXT, '__NULL__'),
    COALESCE(budget::TEXT, '__NULL__')
HAVING COUNT(*) > 1;

-- =============================================================================
-- 8. Reprocessing/idempotency checks
--    Reprocessing must not create duplicate current rows or duplicate natural
--    key + effective_from versions.
-- =============================================================================

CREATE OR REPLACE VIEW audit.v_scd2_reprocessing_idempotency_violations AS
SELECT
    'duplicate_customer_natural_key_effective_from_after_reprocess' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    customer_id AS natural_key,
    STRING_AGG(customer_sk::TEXT, ', ' ORDER BY customer_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'effective_from=' || effective_from || ', duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_customer
WHERE customer_id <> 'UNKNOWN'
GROUP BY customer_id, effective_from
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_product_natural_key_effective_from_after_reprocess' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    product_id AS natural_key,
    STRING_AGG(product_sk::TEXT, ', ' ORDER BY product_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'effective_from=' || effective_from || ', duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_product
WHERE product_id <> 'UNKNOWN'
GROUP BY product_id, effective_from
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_campaign_natural_key_effective_from_after_reprocess' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    campaign_id AS natural_key,
    STRING_AGG(campaign_sk::TEXT, ', ' ORDER BY campaign_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'effective_from=' || effective_from || ', duplicate_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_campaign
WHERE campaign_id <> 'UNKNOWN'
GROUP BY campaign_id, effective_from
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_customer_current_rows_after_reprocess' AS check_name,
    'warehouse.dim_customer' AS checked_entity,
    customer_id AS natural_key,
    STRING_AGG(customer_sk::TEXT, ', ' ORDER BY customer_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'current_row_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_customer
WHERE customer_id <> 'UNKNOWN'
  AND is_current
GROUP BY customer_id
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_product_current_rows_after_reprocess' AS check_name,
    'warehouse.dim_product' AS checked_entity,
    product_id AS natural_key,
    STRING_AGG(product_sk::TEXT, ', ' ORDER BY product_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'current_row_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_product
WHERE product_id <> 'UNKNOWN'
  AND is_current
GROUP BY product_id
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'duplicate_campaign_current_rows_after_reprocess' AS check_name,
    'warehouse.dim_campaign' AS checked_entity,
    campaign_id AS natural_key,
    STRING_AGG(campaign_sk::TEXT, ', ' ORDER BY campaign_sk) AS surrogate_key,
    NULL::TEXT AS fact_key,
    'current_row_count=' || COUNT(*) AS issue_details
FROM warehouse.dim_campaign
WHERE campaign_id <> 'UNKNOWN'
  AND is_current
GROUP BY campaign_id
HAVING COUNT(*) > 1;

-- =============================================================================
-- Audit inserts
-- =============================================================================

WITH run_context AS (
    SELECT
        to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS') AS validation_run_id,
        clock_timestamp() AS checked_at
),
validation_counts AS (
    SELECT
        'SCD2_DIMENSION_INTEGRITY' AS check_category,
        'only_one_current_row_per_natural_key' AS check_name,
        'customer/product/campaign dimensions' AS checked_entity,
        COUNT(*)::BIGINT AS failed_row_count,
        'Each natural key must have exactly one current dimension row.' AS details
    FROM audit.v_scd2_current_row_violations

    UNION ALL

    SELECT
        'SCD2_DIMENSION_INTEGRITY',
        'no_invalid_effective_date_ranges',
        'customer/product/campaign dimensions',
        COUNT(*)::BIGINT,
        'Every SCD2 row must have effective_to greater than effective_from.'
    FROM audit.v_scd2_invalid_effective_range_violations

    UNION ALL

    SELECT
        'SCD2_DIMENSION_INTEGRITY',
        'no_overlapping_effective_date_ranges',
        'customer/product/campaign dimensions',
        COUNT(*)::BIGINT,
        'Historical versions for the same natural key must not overlap.'
    FROM audit.v_scd2_overlapping_range_violations

    UNION ALL

    SELECT
        'SCD2_SURROGATE_KEY_INTEGRITY',
        'no_duplicate_surrogate_keys',
        'customer/product/campaign dimensions',
        COUNT(*)::BIGINT,
        'Surrogate keys must be unique across each SCD2 dimension.'
    FROM audit.v_scd2_duplicate_surrogate_key_violations

    UNION ALL

    SELECT
        'FACT_FOREIGN_KEY_INTEGRITY',
        'no_missing_customer_product_campaign_sk_in_facts',
        'warehouse fact tables',
        COUNT(*)::BIGINT,
        'Facts must not contain NULL or unknown surrogate keys for required SCD2 dimensions.'
    FROM audit.v_scd2_missing_fact_surrogate_key_violations

    UNION ALL

    SELECT
        'POINT_IN_TIME_CORRECTNESS',
        'fact_dates_fall_inside_dimension_effective_ranges',
        'transactional warehouse fact tables joined to SCD2 dimensions',
        COUNT(*)::BIGINT,
        'Transactional fact timestamps must fall inside the effective window of their joined dimension version. Web events and conversions are excluded because behavioral event facts use inferred/current-dimension fallback when no exact SCD2 window exists.'
    FROM audit.v_scd2_fact_date_range_violations

    UNION ALL

    SELECT
        'SCD2_NULL_HANDLING',
        'null_tracked_attributes_do_not_create_duplicate_versions',
        'customer/product/campaign dimensions',
        COUNT(*)::BIGINT,
        'Null-normalized tracked attributes must not create duplicate equivalent SCD2 versions.'
    FROM audit.v_scd2_null_tracked_attribute_violations

    UNION ALL

    SELECT
        'SCD2_REPROCESSING_IDEMPOTENCY',
        'reprocessing_does_not_create_duplicate_current_or_version_rows',
        'customer/product/campaign dimensions',
        COUNT(*)::BIGINT,
        'Reprocessing must not create duplicate current rows or duplicate natural-key/effective-from versions.'
    FROM audit.v_scd2_reprocessing_idempotency_violations
)
INSERT INTO audit.scd2_validation_results (
    validation_run_id,
    check_category,
    check_name,
    checked_entity,
    failed_row_count,
    status,
    severity,
    details,
    checked_at
)
SELECT
    rc.validation_run_id,
    vc.check_category,
    vc.check_name,
    vc.checked_entity,
    vc.failed_row_count,
    CASE
        WHEN vc.failed_row_count = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS status,
    'ERROR' AS severity,
    vc.details,
    rc.checked_at
FROM validation_counts vc
CROSS JOIN run_context rc;

COMMIT;

-- =============================================================================
-- Human-readable output for psql
-- =============================================================================

WITH latest_run AS (
    SELECT validation_run_id
    FROM audit.scd2_validation_results
    ORDER BY checked_at DESC
    LIMIT 1
)
SELECT
    validation_run_id,
    status,
    COUNT(*) AS check_count,
    SUM(failed_row_count) AS total_failed_rows
FROM audit.scd2_validation_results
WHERE validation_run_id = (SELECT validation_run_id FROM latest_run)
GROUP BY validation_run_id, status
ORDER BY status;

WITH latest_run AS (
    SELECT validation_run_id
    FROM audit.scd2_validation_results
    ORDER BY checked_at DESC
    LIMIT 1
)
SELECT
    check_category,
    check_name,
    checked_entity,
    failed_row_count,
    status,
    details
FROM audit.scd2_validation_results
WHERE validation_run_id = (SELECT validation_run_id FROM latest_run)
ORDER BY
    CASE status WHEN 'FAIL' THEN 0 ELSE 1 END,
    check_category,
    check_name;
